test

diff --git a/.github/workflows/build_and_test_ya.yaml b/.github/workflows/build_and_test_ya.yaml
--- a/.github/workflows/build_and_test_ya.yaml
+++ b/.github/workflows/build_and_test_ya.yaml
@@ -237,6 +237,20 @@ jobs:
         SLEEP_AFTER_TESTS: ${{ inputs.sleep_after_tests || '7200' }}
       run: |
         sleep "$SLEEP_AFTER_TESTS"
+  debug:
+    name: Debug
+    runs-on: ${{ fromJson(needs.calculate-runs-on.outputs.runs-on) }}
+    needs: 
+      - calculate-runs-on
+      - build-and-test
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Debug info
+        shell: bash --noprofile --norc -eo pipefail -x {0}
+        run: |
+          echo "Test run outcome: ${needs.build-and-test.outputs.test_run_outcome}"
+          echo "Test failed: ${needs.build-and-test.outputs.test_failed}"
+    
   test-retry:
     name: Retry tests
     runs-on: ${{ fromJson(needs.calculate-runs-on.outputs.runs-on) }}
